# Fish completion for bru
complete -c bru -n '__fish_use_subcommand' -a install -d 'Install a formula'
complete -c bru -n '__fish_use_subcommand' -a uninstall -d 'Uninstall a formula'
complete -c bru -n '__fish_use_subcommand' -a upgrade -d 'Upgrade outdated formulae'
complete -c bru -n '__fish_use_subcommand' -a update -d 'Fetch latest data'
complete -c bru -n '__fish_use_subcommand' -a search -d 'Search for formulae'
complete -c bru -n '__fish_use_subcommand' -a info -d 'Show formula info'
complete -c bru -n '__fish_use_subcommand' -a list -d 'List installed'
complete -c bru -n '__fish_use_subcommand' -a deps -d 'Show dependencies'
complete -c bru -n '__fish_use_subcommand' -a uses -d 'Show reverse deps'
complete -c bru -n '__fish_use_subcommand' -a leaves -d 'Show leaf formulae'
complete -c bru -n '__fish_use_subcommand' -a autoremove -d 'Remove orphaned deps'
complete -c bru -n '__fish_use_subcommand' -a link -d 'Symlink formula'
complete -c bru -n '__fish_use_subcommand' -a unlink -d 'Remove symlinks'
complete -c bru -n '__fish_use_subcommand' -a cleanup -d 'Remove old versions'
complete -c bru -n '__fish_use_subcommand' -a outdated -d 'Show outdated'
complete -c bru -n '__fish_use_subcommand' -a fetch -d 'Download only'
complete -c bru -n '__fish_use_subcommand' -a config -d 'Show config'
